# Generated by Django 3.0.8 on 2020-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('total_rooms', models.IntegerField()),
                ('total_available', models.IntegerField()),
                ('complimentary_brakefast', models.BooleanField()),
            ],
        ),
    ]
