# Generated by Django 3.0.8 on 2020-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='no_of_bed',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rooms',
            name='person_per_room',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
