# Generated by Django 3.0.8 on 2020-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0002_auto_20200729_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
