# Generated by Django 3.0.8 on 2020-07-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0003_rooms_room_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_img',
            new_name='img',
        ),
    ]
