# Generated by Django 3.0.8 on 2020-08-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0004_auto_20200730_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name_plural': 'Room Details'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
