# Generated by Django 3.0.8 on 2020-08-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0006_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Check-in Details'},
        ),
    ]
