# Generated by Django 3.0.8 on 2020-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0007_auto_20200801_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='TotalAmount',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
