# Generated by Django 3.0.8 on 2020-08-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarbourLights', '0009_remove_booking_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='TotalAmount',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
